services:
  # Backend API
  - type: web
    name: markdown-slides-api
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./data/slides_app.db
      - key: OPENAI_API_KEY
        sync: false # Set this manually in Render dashboard

  # Frontend Static Site
  - type: web
    name: markdown-slides-frontend
    env: static
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: frontend/.next
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://markdown-slides-api.onrender.com
